# TODO: add Dockerfile for the histube youtube-downloader web app
# Referenced as local/histube:latest in values/default/media/youtube-downloader.yaml.gotmpl
# Expected: HTTP server on port 8080 with cookie-based yt-dlp integration
