{{- $pod := print .Values.k8s.names.pods.prefix .Values.adguard.label .Values.k8s.names.pods.suffix }}
{{- $appVolume := "app-volume" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $pod }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $pod }}
  template:
    metadata:
      labels:
        app: {{ $pod }}
    spec:
      containers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ .Values.adguard.label }}{{ .Values.k8s.names.containers.suffix }}
        image: {{ .Values.adguard.image }}
        ports:
        - containerPort: {{ .Values.adguard.ports.dnsTcp.targetPort }}
        - containerPort: {{ .Values.adguard.ports.http.targetPort }}
        - containerPort: {{ .Values.adguard.ports.admin.targetPort }}
        env:
        - name: AGH_CONFIG
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.k8s.names.configMaps.prefix }}{{ .Values.adguard.label }}{{ .Values.k8s.names.configMaps.suffix }}
              key: AdGuardHome.yaml
        volumeMounts:
        - mountPath: /opt/adguardhome/work
          name: {{ $appVolume }}
          subPath: adguard
      volumes:
      - name: {{ $appVolume }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.adguard.pvc . }}
