{{- $pod := print .Values.k8s.names.pods.prefix (tpl .Values.observability.otelCollector.collectors.label $) .Values.k8s.names.pods.suffix }}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $pod }}
  namespace: {{ tpl .Values.observability.otelCollector.collectors.namespace . }}
spec:
  selector:
    matchLabels:
      app: {{ $pod }}
  template:
    metadata:
      labels:
        app: {{ $pod }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/observability/nodes-collectors/config-map.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Values.k8s.names.serviceAccounts.prefix }}{{ tpl .Values.observability.otelCollector.collectors.label . }}{{ .Values.k8s.names.serviceAccounts.suffix }}
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ tpl .Values.observability.otelCollector.collectors.label . }}{{ .Values.k8s.names.containers.suffix }}
        image: {{ .Values.observability.otelCollector.image }}
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 400Mi
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: conf
          mountPath: /conf/collector.yaml
          subPath: collector.yaml
          mountPropagation: HostToContainer
        # mount /hostfs for host metrics
        - name: hostfs
          mountPath: /hostfs
          readOnly: true
        args: ["--config=/conf/collector.yaml"]
        ports:
        - containerPort: {{ .Values.observability.otelCollector.collectors.ports.grpc.targetPort }}
        - containerPort: {{ .Values.observability.otelCollector.collectors.ports.http.targetPort }}
      volumes:
      - name: hostfs
        hostPath:
          path: /
      - name: conf
        configMap:
          name: {{ .Values.k8s.names.configMaps.prefix }}{{ tpl .Values.observability.otelCollector.collectors.label . }}{{ .Values.k8s.names.configMaps.suffix }}
