resources:
  homarr-ingress:
    type: kubernetes:networking.k8s.io/v1:Ingress
    options:
      dependsOn:
      - ${homarr-service}
    properties:
      metadata:
        namespace: ${k8s.namespace}
        name: ${names.ingresses.homarr}
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: ${traefik.ports.https.name}
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.tls.certresolver: ${traefik.tls-resolver-name}
          pulumi.com/skipAwait: "true"

      spec:
        rules:
          - host: ${hosts.homarr}
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: ${names.services.homarr}
                      port:
                        number: ${homarr.ports.http.targetPort}
