{{- if .Values.jellyfin.enable }}

{{- $pod := print .Values.k8s.names.pods.prefix .Values.jellyfin.label .Values.k8s.names.pods.suffix }}
{{- $appVolume := "app-volume" }}
{{- $configMap := "config-map" }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $pod }}
  labels:
    app: {{ $pod }}

spec:
  replicas: {{ .Values.jellyfin.replicasNb }}
  selector:
    matchLabels:
      app: {{ $pod }}
  template:
    metadata:
      labels:
        app: {{ $pod }}
    spec:
      containers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ .Values.jellyfin.label }}{{ .Values.k8s.names.containers.suffix }}
        image: {{ .Values.jellyfin.image }}
        resources:
          {{- toYaml .Values.jellyfin.resources | nindent 10 }}
        ports:
        - name: {{ .Values.jellyfin.ports.http.name }}
          containerPort: {{ .Values.jellyfin.ports.http.targetPort }}
        env:
        - name: API_KEY
          value: "{{ .Values.jellyfin.apiKey }}"
        - name: LOG_LEVEL
          value: "{{ .Values.jellyfin.logLevel }}"
        - name: DB_TYPE
          value: "{{ .Values.jellyfin.database.type }}"
        - name: DB_HOST
          value: "{{ .Values.jellyfin.database.host }}"
        - name: DB_PORT
          value: "{{ .Values.jellyfin.database.port }}"
        - name: DB_USER
          value: "{{ .Values.jellyfin.database.username }}"
        - name: DB_PASS
          value: "{{ .Values.jellyfin.database.password }}"
        - name: DB_NAME
          value: "{{ .Values.jellyfin.database.name }}"
        - name: DB_LOG_QUERIES
          value: "{{ .Values.jellyfin.database.logQueries }}"
        - name: PORT
          value: "{{ .Values.jellyfin.ports.http.targetPort }}"
        volumeMounts:
        - mountPath: /app/config
          name: {{ $appVolume }}
          subPath: jellyfin/config
        - mountPath: /settings.json
          name: {{ $configMap }}
          subPath: settings.json
      volumes:
      - name: {{ $appVolume }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.jellyfin.pvc . }}
      - name: {{ $configMap }}
        configMap:
          name: {{ .Values.k8s.names.configMaps.prefix }}{{ .Values.jellyfin.label }}{{ .Values.k8s.names.configMaps.suffix }}

{{- end }}
