{{- if .Values.jellyfin.enabled }}
{{- if .Values.jellyfin.enable }}

apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.k8s.names.services.prefix }}{{ .Values.jellyfin.label }}{{ .Values.k8s.names.services.suffix }}

spec:
  ports:
  - protocol: TCP
    name: {{ .Values.jellyfin.ports.http.name }}
    port: {{ .Values.jellyfin.ports.http.targetPort }}
  selector:
    app: {{ .Values.k8s.names.pods.prefix }}{{ .Values.jellyfin.label }}{{ .Values.k8s.names.pods.suffix }}

{{- end }}
{{- end }}
