apiVersion: v1
kind: Secret

type: kubernetes.io/service-account-token

metadata:
  name: {{ .Values.k8s.names.secrets.prefix }}{{ .Values.homepage.label }}{{ .Values.k8s.names.secrets.suffix }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.k8s.names.serviceAccounts.prefix }}{{ .Values.homepage.label }}{{ .Values.k8s.names.serviceAccounts.suffix }}
