apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ .Values.k8s.names.serviceAccounts.prefix }}{{ .Values.homepage.label }}{{ .Values.k8s.names.serviceAccounts.suffix }}
secrets:
  - name: {{ .Values.k8s.names.secrets.prefix }}{{ .Values.homepage.label }}{{ .Values.k8s.names.secrets.suffix }}
