{{- if or .Values.observability.otelCollector.gateway.enable .Values.observability.otelCollector.collectors.enable }}
apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ .Values.k8s.names.serviceAccounts.prefix }}{{ .Values.observability.otelCollector.label }}{{ .Values.k8s.names.serviceAccounts.suffix }}
{{- end }}
