apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.radarr.names.configMap }}

data:
  config.xml: |
    <Config>
      <BindAddress>*</BindAddress>
      <Port>{{ .Values.radarr.ports.http.targetPort }}</Port>
      <SslPort>9898</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>True</LaunchBrowser>
      <ApiKey>{{ .Values.radarr.apiKey }}</ApiKey>
      <AuthenticationMethod>External</AuthenticationMethod>
      <AuthenticationRequired>DisabledForLocalAddresses</AuthenticationRequired>
      <Branch>master</Branch>
      <LogLevel>info</LogLevel>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase></UrlBase>
      <InstanceName>Radarr</InstanceName>
      <UpdateMechanism>Docker</UpdateMechanism>
      <PostgresHost>{{ .Values.media.database.names.service }}</PostgresHost>
      <PostgresPort>{{ .Values.media.database.ports.http.targetPort }}</PostgresPort>
      <PostgresUser>{{ .Values.media.database.credentials.username }}</PostgresUser>
      <PostgresPassword>{{ .Values.media.database.credentials.password }}</PostgresPassword>
      <PostgresMainDb>{{ .Values.media.database.databases.radarr.main }}</PostgresMainDb>
      <PostgresLogDb>{{ .Values.media.database.databases.radarr.logs }}</PostgresLogDb>
    </Config>
