{{- if .Values.radarr.enable }}
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.k8s.names.services.prefix }}{{ .Values.radarr.label }}{{ .Values.k8s.names.services.suffix }}

spec:
  ports:
  - protocol: TCP
    name: {{ .Values.radarr.ports.http.name }}
    port: {{ .Values.radarr.ports.http.targetPort }}
  selector:
    app: {{ .Values.k8s.names.pods.prefix }}{{ .Values.radarr.label }}{{ .Values.k8s.names.pods.suffix }}
{{- end }}
