apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.traefik.names.pod }}
  labels:
    app: {{ .Values.traefik.names.pod }}

spec:
  replicas: {{ .Values.traefik.replicasNb }}
  selector:
    matchLabels:
      app: {{ .Values.traefik.names.pod }}
  template:
    metadata:
      labels:
        app: {{ .Values.traefik.names.pod }}
    spec:
      serviceAccountName: {{ .Values.traefik.names.serviceAccount }}
      containers:
      - name: {{ .Values.traefik.names.container }}
        image: {{ .Values.traefik.image.registry }}{{ .Values.traefik.image.namespace }}{{ .Values.traefik.image.repository }}:{{ .Values.traefik.image.tag }}
        args:
          # provider: file
          - --providers.file.directory=/file-providers
          # provider: kubernetesCRD (required for authelia middleware)
          - --providers.kubernetescrd=true
          # provider: kubernetes
          - --providers.kubernetesingress.allowEmptyServices=true
          - --providers.kubernetesingress.labelselector=chartVersion={{ .Chart.Version }},env={{ .Values.project.env }}
          - --providers.kubernetesingress.namespaces={{ .Values.k8s.namespace }}
          # dashboard
          - --api.insecure=true
          # logging
          - --log.level={{ .Values.traefik.logging.level }}
          - --log.format={{ .Values.traefik.logging.format }}
          - --accesslog
          # letsencrypt resolver
          {{ if .Values.acme.challenge.dns.enable }}
          - --certificatesresolvers.{{ .Values.traefik.resolverName }}.acme.dnschallenge=true
          {{ end }}
          {{ if .Values.acme.challenge.tls.enable }}
          - --certificatesresolvers.{{ .Values.traefik.resolverName }}.acme.tlschallenge=true
          {{ end }}
          - --certificatesresolvers.{{ .Values.traefik.resolverName }}.acme.email={{ .Values.acme.email }}
          - --certificatesresolvers.{{ .Values.traefik.resolverName }}.acme.storage=/etc/traefik/acme/acme.json
          - --certificatesresolvers.{{ .Values.traefik.resolverName }}.acme.caserver={{ .Values.acme.endpoint }}
          # entrypoints
          - --entryPoints.{{ .Values.traefik.ports.dashboard.name }}.address=:{{ .Values.traefik.ports.dashboard.targetPort }}
          - --entryPoints.{{ .Values.traefik.ports.https.name }}.address=:{{ .Values.traefik.ports.https.targetPort }}
        env:
          {{ if .Values.acme.challenge.dns.enable }}
          {{- toYaml .Values.acme.challenge.dns.env | nindent 5}}
          {{ end }}
        ports:
        - name: {{ .Values.traefik.ports.https.name }}
          containerPort: {{ .Values.traefik.ports.https.targetPort }}
        - name: {{ .Values.traefik.ports.dashboard.name }}
          containerPort: {{ .Values.traefik.ports.dashboard.targetPort }}
        volumeMounts:
        - mountPath: /file-providers/jellyfin-local-proxy.yaml
          name: {{ .Values.traefik.names.configMap }}
          subPath: jellyfin-file-provider.yaml
        - mountPath: /etc/traefik/acme
          name: {{ .Values.traefik.storage.pv }}
          subPath: apps/traefik/acme
      volumes:
      - name: {{ .Values.traefik.names.configMap }}
        configMap:
          name: {{ .Values.traefik.names.configMap }}
      - name: {{ .Values.traefik.storage.pv }}
        persistentVolumeClaim:
          claimName: {{ .Values.traefik.storage.pvc }}

