apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: {{ .Values.k8s.names.ingresses.prefix }}{{ .Values.observability.logs.label }}{{ .Values.k8s.names.ingresses.suffix }}
  labels:
    chartVersion: {{ .Chart.Version }}
    env: {{ .Values.project.env }}

spec:
  entryPoints:
  - {{ .Values.traefik.ports.https.name }}

  routes:
  - kind: Rule
    match: Host(`{{ tpl .Values.observability.logs.host . }}`)
    middlewares:
    - name: {{ .Values.k8s.names.middlewares.prefix }}{{ .Values.authelia.label }}{{ .Values.k8s.names.middlewares.suffix }}
      namespace: {{ .Values.k8s.namespace }}
    services:
    - kind: Service
      name: {{ .Values.k8s.names.services.prefix }}{{ .Values.observability.logs.label }}{{ .Values.k8s.names.services.suffix }}
      port: {{ .Values.observability.logs.ports.http.targetPort }}

  {{- if or .Values.traefik.tls.selfSigned .Values.traefik.tls.wildcard }}
  tls:
    store:
      name: default
  {{- else }}
  tls:
    certResolver: {{ .Values.traefik.resolverName }}
  {{- end }}
