{{- if .Values.observability.logs.enable }}
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.k8s.names.services.prefix }}{{ .Values.observability.logs.label }}{{ .Values.k8s.names.services.suffix }}

spec:
  ports:
  - protocol: TCP
    name: {{ .Values.observability.logs.ports.grpc.name }}
    port: {{ .Values.observability.logs.ports.grpc.targetPort }}
    targetPort: {{ .Values.observability.logs.ports.grpc.targetPort }}
  - protocol: TCP
    name: {{ .Values.observability.logs.ports.http.name }}
    port: {{ .Values.observability.logs.ports.http.targetPort }}
    targetPort: {{ .Values.observability.logs.ports.http.targetPort }}
  selector:
    app: {{ .Values.k8s.names.pods.prefix }}{{ .Values.observability.logs.label }}{{ .Values.k8s.names.pods.suffix }}
{{- end }}
