{{- if .Values.sphaze.enable }}
{{- $pod := print .Values.k8s.names.pods.prefix .Values.sphaze.label .Values.k8s.names.pods.suffix }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $pod }}
  labels:
    app: {{ $pod }}

spec:
  replicas: {{ .Values.sphaze.replicasNb }}
  selector:
    matchLabels:
      app: {{ $pod }}
  template:
    metadata:
      labels:
        app: {{ $pod }}
    spec:
      containers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ .Values.sphaze.label }}{{ .Values.k8s.names.containers.suffix }}
        image: {{ .Values.sphaze.image }}
        resources:
          {{- toYaml .Values.sphaze.resources | nindent 10 }}
        ports:
        - name: {{ .Values.sphaze.ports.http.name }}
          containerPort: {{ .Values.sphaze.ports.http.targetPort }}
{{- end }}
