{{- $pod := print .Values.k8s.names.pods.prefix .Values.authelia.label .Values.k8s.names.pods.suffix }}
{{- $configMap := "config-map" }}
{{- $appVolume := "app-volume" }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $pod }}
  labels:
    app: {{ $pod }}

spec:
  replicas: {{ .Values.authelia.replicasNb }}
  selector:
    matchLabels:
      app: {{ $pod }}
  template:
    metadata:
      labels:
        app: {{ $pod }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/authelia/authelia--config-map.yaml") . | sha256sum }}
    spec:
      enableServiceLinks: false
      containers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ .Values.authelia.label }}{{ .Values.k8s.names.containers.suffix }}
        image: {{ .Values.authelia.image }}
        ports:
        - name: {{ .Values.authelia.ports.http.name }}
          containerPort: {{ .Values.authelia.ports.http.targetPort }}
        - name: {{ .Values.authelia.ports.metrics.name }}
          containerPort: {{ .Values.authelia.ports.metrics.targetPort }}
        volumeMounts:
        - mountPath: /config
          name: {{ $appVolume }}
          subPath: authelia/config
      initContainers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ .Values.authelia.label }}-init{{ .Values.k8s.names.containers.suffix }}
        image: busybox:1.28
        command: ['sh', '-c', '/setup.sh']
        volumeMounts:
        - mountPath: /config
          name: {{ $appVolume }}
          subPath: authelia/config
        - mountPath: /setup.sh
          name: {{ $configMap }}
          subPath: setup.sh
        - mountPath: /users_database.yml
          name: {{ $configMap }}
          subPath: users_database.yml
        - mountPath: /configuration.yml
          name: {{ $configMap }}
          subPath: configuration.yml
      volumes:
      - name: {{ $appVolume }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.authelia.storage.pvc . }}
      - name: {{ $configMap }}
        configMap:
          name: {{ .Values.k8s.names.configMaps.prefix }}{{ .Values.authelia.label }}{{ .Values.k8s.names.configMaps.suffix }}
          defaultMode: 0500
