apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.k8s.names.configMaps.prefix }}{{ .Values.observability.otelCollector.gateway.label }}{{ .Values.k8s.names.configMaps.suffix }}
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:{{ .Values.observability.otelCollector.gateway.ports.grpc.targetPort }}
          http:
            endpoint: 0.0.0.0:{{ .Values.observability.otelCollector.gateway.ports.http.targetPort }}
      {{- if .Values.observability.otelCollector.receivers.k8sCluster.enable }}
      k8s_cluster:
        auth_type: serviceAccount
        node_conditions_to_report:
        - Ready
        - MemoryPressure
        allocatable_types_to_report:
        - cpu
        - memory
      {{- end }}
      {{- if .Values.observability.otelCollector.receivers.jellyfinCustom.enable }}
      prometheus/jellyfinCustom:
        config:
          scrape_configs:
          - job_name: jellyfin-api
            scrape_interval: 30s
            metrics_path: /probe
            params:
              module: [jellyfin]
            static_configs:
            - targets:
              {{- if .Values.jellyfin.proxy.enable }}
              - http://{{ .Values.jellyfin.proxy.host }}:{{ .Values.jellyfin.proxy.port }}/Sessions
              {{- end }}
              {{- if .Values.jellyfin.enable }}
              - https://{{ .Values.jellyfin.host }}/Sessions
              {{- end }}
            relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: {{ .Values.k8s.names.services.prefix }}{{ .Values.observability.prometheusJsonExporter.label }}{{ .Values.k8s.names.services.suffix }}:{{ .Values.observability.prometheusJsonExporter.ports.http.targetPort }}
      {{- end }}
      {{- if .Values.observability.otelCollector.receivers.jellyfinNative.enable }}
      prometheus/jellyfinNative:
        config:
          scrape_configs:
          - job_name: 'jellyfin-metrics'
            scrape_interval: 30s
            static_configs:
            - targets:
              {{- if .Values.jellyfin.enable }}
              - {{ .Values.jellyfin.host }}
              {{- end }}
              {{- if .Values.jellyfin.proxy.enable }}
              - {{ .Values.jellyfin.proxy.host }}:{{ .Values.jellyfin.proxy.port }}
              {{- end }}
      {{- end }}
      {{- if .Values.observability.otelCollector.receivers.synologySnmp.enable }}
      prometheus/synologySnmp:
        config:
          scrape_configs:
          - job_name: 'synology-disk-station'
            metrics_path: /snmp
            params:
              module: [synology]
              auth: [synology_v3]
            scrape_interval: 30s
            scrape_timeout: 30s
            static_configs:
            - targets:
              - {{ .Values.observability.otelCollector.receivers.synologySnmp.url }}
            relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                replacement: {{ .Values.k8s.names.services.prefix }}{{ .Values.observability.prometheusSnmpExporter.label }}{{ .Values.k8s.names.services.suffix }}:{{ .Values.observability.prometheusSnmpExporter.ports.http.targetPort }}
      {{- end }}

    processors:
      batch:
        timeout: 5s
        send_batch_size: 512
        send_batch_max_size: 2048
      memory_limiter:
        check_interval: 1s
        limit_mib: 4000
        spike_limit_mib: 800
      attributes/otlp:
        actions:
        - key: gateway-receiver
          value: otlp
          action: insert
      attributes/prometheus:
        actions:
        - key: gateway-receiver
          value: prometheus
          action: insert
      attributes/k8s_cluster:
        actions:
        - key: gateway-receiver
          value: k8s_cluster
          action: insert
      attributes/snmp:
        actions:
        - key: gateway-receiver
          value: snmp
          action: insert
      attributes/add_labels_to_nas:
        actions:
          - key: instance
            action: insert
            value: nasypod
          - key: job
            action: insert
            value: nas

    exporters:
      debug/verbose:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200
      debug/noop:
        verbosity: normal
        sampling_initial: 0
        sampling_thereafter: 0
      otlphttp/victoriametrics:
        compression: gzip
        encoding: proto
        metrics_endpoint: http://{{ .Values.k8s.names.services.prefix }}{{ .Values.observability.metrics.label }}{{ .Values.k8s.names.services.suffix }}:{{ .Values.observability.metrics.ports.http.targetPort }}/opentelemetry/v1/metrics
        tls:
          insecure: true
      loki:
        endpoint: http://{{ .Values.k8s.names.services.prefix }}{{ .Values.observability.logs.label }}{{ .Values.k8s.names.services.suffix }}:{{ .Values.observability.logs.ports.http.targetPort }}/loki/api/v1/push
        tls:
          insecure: true
      otlphttp/tempo:
        compression: gzip
        encoding: proto
        traces_endpoint: http://{{ .Values.k8s.names.services.prefix }}{{ .Values.observability.traces.label }}{{ .Values.k8s.names.services.suffix }}:{{ .Values.observability.traces.ports.http.targetPort }}/v1/traces
        tls:
          insecure: true

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [loki]

        metrics/otlp:
          receivers: [otlp]
          processors: [attributes/otlp, batch, memory_limiter]
          exporters: [otlphttp/victoriametrics]
        {{- if .Values.observability.otelCollector.receivers.jellyfinCustom.enable }}
        metrics/jellyfinCustom:
          receivers: [prometheus/jellyfinCustom]
          processors: [attributes/prometheus, batch, memory_limiter]
          exporters: [otlphttp/victoriametrics]
        {{- end }}
        {{- if .Values.observability.otelCollector.receivers.jellyfinNative.enable }}
        metrics/jellyfinNative:
          receivers: [prometheus/jellyfinNative]
          processors: [attributes/prometheus, batch, memory_limiter]
          exporters: [otlphttp/victoriametrics]
        {{- end }}
        {{- if .Values.observability.otelCollector.receivers.k8sCluster.enable }}
        metrics/k8s_cluster:
          receivers: [k8s_cluster]
          processors: [attributes/k8s_cluster, batch, memory_limiter]
          exporters: [otlphttp/victoriametrics]
        {{- end }}
        {{- if .Values.observability.otelCollector.receivers.synologySnmp.enable }}
        metrics/synologySnmp:
          receivers: [prometheus/synologySnmp]
          processors: [attributes/snmp, attributes/add_labels_to_nas, batch, memory_limiter]
          exporters: [otlphttp/victoriametrics]
        {{- end }}

        traces:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [otlphttp/tempo]
