apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.k8s.names.configMaps.prefix }}{{ .Values.observability.opentelemetryCollector.gateway.label }}{{ .Values.k8s.names.configMaps.suffix }}
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:{{ .Values.observability.opentelemetryCollector.gateway.ports.grpc.targetPort }}
          http:
            endpoint: 0.0.0.0:{{ .Values.observability.opentelemetryCollector.gateway.ports.http.targetPort }}
      {{- if .Values.observability.receivers.k8sCluster.enable }}
      k8s_cluster:
        auth_type: serviceAccount
        node_conditions_to_report:
        - Ready
        - MemoryPressure
        allocatable_types_to_report:
        - cpu
        - memory
      {{- end }}
      {{- if .Values.observability.receivers.jellyfinCustom.enable }}
      prometheus/jellyfinCustom:
        config:
          scrape_configs:
          - job_name: jellyfin-jellyfinCustomStats
            scrape_interval: 30s
            metrics_path: /probe
            params:
              module: [jellyfin]
            static_configs:
            - targets:
              {{- if .Values.jellyfin.proxy.enable }}
              - http://{{ .Values.jellyfin.proxy.host }}:{{ .Values.jellyfin.proxy.port }}/Sessions
              {{- end }}
              {{- if .Values.jellyfin.enable }}
              - https://{{ .Values.jellyfin.host }}/Sessions
              {{- end }}
            relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: {{ .Values.k8s.names.services.prefix }}{{ .Values.observability.jellyfinCustomStats.label }}{{ .Values.k8s.names.services.suffix }}:{{ .Values.observability.jellyfinCustomStats.ports.http.targetPort }}
      {{- end }}
      {{- if .Values.observability.receivers.jellyfinNative.enable }}
      prometheus/jellyfinNative:
        config:
          scrape_configs:
          - job_name: 'jellyfin-native'
            scrape_interval: 30s
            static_configs:
            - targets:
              {{- if .Values.jellyfin.enable }}
              - https://{{ .Values.jellyfin.host }}/Sessions
              {{- end }}
              {{- if .Values.jellyfin.proxy.enable }}
              - https://{{ .Values.jellyfin.proxy.host }}:{{ .Values.jellyfin.proxy.port }}/Sessions
              {{- end }}
      {{- end }}
      {{- if .Values.observability.receivers.snmp.enable }}
      snmp:
        collection_interval: 60s
        timeout: 3s
        endpoint: {{ .Values.observability.receivers.snmp.url }}
        version: v3
        security_level: auth_priv
        user: {{ .Values.observability.receivers.snmp.credentials.username }}
        auth_type: SHA
        auth_password: {{ .Values.observability.receivers.snmp.credentials.password }}
        privacy_type: AES
        privacy_password: {{ .Values.observability.receivers.snmp.credentials.password }}
        metrics: {{ .Values.observability.receivers.snmp.metrics | toYaml | nindent 10 }}
      {{- end }}

    processors:
      batch:
        timeout: 5s
        send_batch_size: 512
        send_batch_max_size: 2048
      memory_limiter:
        check_interval: 1s
        limit_mib: 4000
        spike_limit_mib: 800
      attributes/otlp:
        actions:
        - key: gateway-receiver
          value: otlp
          action: insert
      attributes/prometheus:
        actions:
        - key: gateway-receiver
          value: prometheus
          action: insert
      attributes/k8s_cluster:
        actions:
        - key: gateway-receiver
          value: k8s_cluster
          action: insert
      attributes/snmp:
        actions:
        - key: gateway-receiver
          value: snmp
          action: insert
      attributes/add_labels_to_nas:
        actions:
          - key: instance
            action: insert
            value: nasypod
          - key: job
            action: insert
            value: nas

    exporters:
      debug/verbose:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200
      debug/noop:
        verbosity: normal
        sampling_initial: 0
        sampling_thereafter: 0
      otlphttp/victoriametrics:
        compression: gzip
        encoding: proto
        metrics_endpoint: http://{{ .Values.k8s.names.services.prefix }}{{ .Values.observability.metrics.label }}{{ .Values.k8s.names.services.suffix }}:{{ .Values.observability.metrics.ports.http.targetPort }}/opentelemetry/v1/metrics
        tls:
          insecure: true
      loki:
        endpoint: http://{{ .Values.k8s.names.services.prefix }}{{ .Values.observability.logs.label }}{{ .Values.k8s.names.services.suffix }}:{{ .Values.observability.logs.ports.http.targetPort }}/loki/api/v1/push
        tls:
          insecure: true
      otlphttp/tempo:
        compression: gzip
        encoding: proto
        traces_endpoint: http://{{ .Values.k8s.names.services.prefix }}{{ .Values.observability.traces.label }}{{ .Values.k8s.names.services.suffix }}:{{ .Values.observability.traces.ports.http.targetPort }}/v1/traces
        tls:
          insecure: true

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [loki]

        metrics/otlp:
          receivers: [otlp]
          processors: [attributes/otlp, batch, memory_limiter]
          exporters: [otlphttp/victoriametrics]
        {{- if .Values.observability.receivers.jellyfinCustom.enable }}
        metrics/jellyfinCustom:
          receivers: [prometheus/jellyfinCustom]
          processors: [attributes/prometheus, batch, memory_limiter]
          exporters: [otlphttp/victoriametrics]
        {{- end }}
        {{- if .Values.observability.receivers.jellyfinNative.enable }}
        metrics/jellyfinNative:
          receivers: [prometheus/jellyfinNative]
          processors: [attributes/prometheus, batch, memory_limiter]
          exporters: [otlphttp/victoriametrics]
        {{- end }}
        {{- if .Values.observability.receivers.k8sCluster.enable }}
        metrics/k8s_cluster:
          receivers: [k8s_cluster]
          processors: [attributes/k8s_cluster, batch, memory_limiter]
          exporters: [otlphttp/victoriametrics]
        {{- end }}
        {{- if .Values.observability.receivers.snmp.enable }}
        metrics/snmp:
          receivers: [snmp]
          processors: [attributes/snmp, attributes/add_labels_to_nas, batch, memory_limiter]
          exporters: [otlphttp/victoriametrics]
        {{- end }}

        traces:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [otlphttp/tempo]
