traefik:
  domain: example.com
  host: ${k8s.names.urls.prefix}${traefik.label}${k8s.names.urls.suffix}.${traefik.domain}
  image:
    registry: docker.io/
    namespace: ""
    repository: traefik
    tag: v3.1
  label: traefik
  dashboardLabel: traefik-dashboard
  logging:
    format: common
    level: ERROR
  ports:
    dashboard:
      # name has to be traefik, see https://doc.traefik.io/traefik/operations/api/#insecure
      name: traefik
      port: 9999
      targetPort: 9999
    https:
      name: https
      port: 443
      targetPort: 443
  replicasNb: 1
  resolverName: letsencrypt
  storage:
    pvc: ${storage.defaultVolumes.apps}
