{{- $pod := print .Values.k8s.names.pods.prefix .Values.database.label .Values.k8s.names.pods.suffix }}
{{- $appVolume := "app-volume" }}
{{- $configMap := "config-map" }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $pod }}
  labels:
    app: {{ $pod }}

spec:
  replicas: {{ .Values.database.replicasNb }}
  selector:
    matchLabels:
      app: {{ $pod }}
  template:
    metadata:
      labels:
        app: {{ $pod }}
    spec:
      containers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ .Values.database.label }}{{ .Values.k8s.names.containers.suffix }}
        image: {{ .Values.database.image }}
        ports:
        - name: {{ .Values.database.ports.http.name }}
          containerPort: {{ .Values.database.ports.http.targetPort }}
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.database.credentials.username }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.database.credentials.password }}"
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/init-db.sh
          name: {{ $configMap }}
          subPath: init-db.sh
        - mountPath: /var/lib/postgresql/data
          name: {{ $appVolume }}
          subPath: media/db
      volumes:
      - name: {{ $configMap }}
        configMap:
          name: {{ .Values.k8s.names.configMaps.prefix }}{{ .Values.database.label }}{{ .Values.k8s.names.configMaps.suffix }}
      - name: {{ $appVolume }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.database.pvc . }}
