apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.whoami.names.pod }}
  labels:
    app: {{ .Values.whoami.names.pod }}

spec:
  replicas: {{ .Values.whoami.replicasNb }}
  selector:
    matchLabels:
      app: {{ .Values.whoami.names.pod }}
  template:
    metadata:
      labels:
        app: {{ .Values.whoami.names.pod }}
    spec:
      containers:
      - name: {{ .Values.whoami.names.container }}
        image: {{ .Values.whoami.image }}
        ports:
        - name: {{ .Values.whoami.ports.http.name }}
          containerPort: {{ .Values.whoami.ports.http.targetPort }}
