{{- $pod := print .Values.k8s.names.pods.prefix .Values.observability.traces.label .Values.k8s.names.pods.suffix }}
{{- $appVolume := "app-volume" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $pod }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $pod }}
  template:
    metadata:
      labels:
        app: {{ $pod }}
    spec:
      initContainers:
      - name: init-permissions
        image: busybox:1.37.0
        command: ['sh', '-c', 'mkdir -p /data/tempo/var /data/tempo/etc && chown -R 10001:10001 /data/tempo']
        volumeMounts:
        - name: {{ $appVolume }}
          mountPath: /data
      containers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ .Values.observability.traces.label }}{{ .Values.k8s.names.containers.suffix }}
        image: {{ .Values.observability.traces.image }}
        resources:
          {{- toYaml .Values.observability.traces.resources | nindent 10 }}
        args: [ "-config.file=/etc/tempo.yaml" ]
        ports:
        - containerPort: {{ .Values.observability.traces.ports.http.targetPort }}
        - containerPort: {{ .Values.observability.traces.ports.grpc.targetPort }}
        volumeMounts:
        - name: conf
          mountPath: /etc/tempo.yaml
          subPath: tempo.yaml
        - mountPath: /var/tempo
          name: {{ $appVolume }}
          subPath: tempo/var
        - mountPath: /etc/tempo
          name: {{ $appVolume }}
          subPath: tempo/etc
      volumes:
      - name: {{ $appVolume }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.observability.pvc . }}
      - name: conf
        configMap:
          name: {{ .Values.k8s.names.configMaps.prefix }}{{ .Values.observability.traces.label }}{{ .Values.k8s.names.configMaps.suffix }}
