{{- if .Values.dbeaver.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: {{ .Values.k8s.names.ingresses.prefix }}{{ .Values.dbeaver.label }}{{ .Values.k8s.names.ingresses.suffix }}

spec:
  entryPoints:
  - {{ .Values.traefik.ports.https.name }}

  routes:
  - kind: Rule
    match: Host(`{{ tpl .Values.dbeaver.host . }}`)
    middlewares:
    - name: {{ .Values.k8s.names.middlewares.prefix }}{{ .Values.authelia.label }}{{ .Values.k8s.names.middlewares.suffix }}
      namespace: {{ .Values.k8s.namespace }}
    services:
    - kind: Service
      name: {{ .Values.k8s.names.services.prefix }}{{ .Values.dbeaver.label }}{{ .Values.k8s.names.services.suffix }}
      port: {{ .Values.dbeaver.ports.http.targetPort }}

  {{- if .Values.traefik.tls.selfSigned }}
  tls:
    store:
      name: default
  {{- else }}
  tls:
    certResolver: {{ .Values.traefik.resolverName }}
  {{- end }}
{{- end }}
