apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.k8s.names.configMaps.prefix }}{{ .Values.dbeaver.label }}{{ .Values.k8s.names.configMaps.suffix }}

data:
  initial-data.conf: |
    {
      adminName: "{{ $.Values.dbeaver.credentials.username }}",
      adminPassword: "{{ $.Values.dbeaver.credentials.password }}",
      teams: [
        {
          subjectId: "admin",
          teamName: "Admin",
          description: "Administrative access. Has total and full authority.",
          permission: ["admin"]
        },
        {
          subjectId: "user",
          teamName: "User",
          description: "Standard user",
          permission: []
        }
      ]
    }
