{{- $pod := print .Values.k8s.names.pods.prefix .Values.readarr.label .Values.k8s.names.pods.suffix }}
{{- $configMap := "config-map" }}
{{- $appVolume := "app-volume" }}
{{- $mediaVolume := "media-volume" }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $pod }}
  labels:
    app: {{ $pod }}

spec:
  replicas: {{ .Values.readarr.replicasNb }}
  selector:
    matchLabels:
      app: {{ $pod }}
  template:
    metadata:
      labels:
        app: {{ $pod }}
    spec:
      containers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ .Values.readarr.label }}{{ .Values.k8s.names.containers.suffix }}
        image: {{ .Values.readarr.image }}
        ports:
        - name: {{ .Values.readarr.ports.http.name }}
          containerPort: {{ .Values.readarr.ports.http.targetPort }}
        env:
        - name: PUID
          value: "{{ .Values.media.system.userId }}"
        - name: PGID
          value: "{{ .Values.media.system.groupId }}"
        - name: UMASK
          value: "{{ .Values.media.system.umask }}"
        volumeMounts:
        - mountPath: /config
          name: {{ $appVolume }}
          subPath: readarr/config
        - mountPath: /config/config.xml
          name: {{ $configMap }}
          subPath: config.xml
        - mountPath: {{ .Values.media.system.data.path }}
          name: {{ $mediaVolume }}
      volumes:
      - name: {{ $mediaVolume }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.readarr.pvc.media . }}
      - name: {{ $appVolume }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.readarr.pvc.app . }}
      - name: {{ $configMap }}
        configMap:
          name: {{ .Values.k8s.names.configMaps.prefix }}{{ .Values.readarr.label }}{{ .Values.k8s.names.configMaps.suffix }}
