{{- if .Values.readarr.enable }}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.k8s.names.configMaps.prefix }}{{ .Values.readarr.label }}{{ .Values.k8s.names.configMaps.suffix }}

data:
  config.xml: |
    <Config>
      <BindAddress>*</BindAddress>
      <Port>{{ .Values.readarr.ports.http.targetPort }}</Port>
      <SslPort>9898</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>True</LaunchBrowser>
      <ApiKey>{{ .Values.readarr.apiKey }}</ApiKey>
      <AuthenticationMethod>External</AuthenticationMethod>
      <AuthenticationRequired>DisabledForLocalAddresses</AuthenticationRequired>
      <Branch>master</Branch>
      <LogLevel>info</LogLevel>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase></UrlBase>
      <InstanceName>readarr</InstanceName>
      <UpdateMechanism>Docker</UpdateMechanism>
      <PostgresHost>{{ .Values.k8s.names.services.prefix }}{{ .Values.database.label }}{{ .Values.k8s.names.services.suffix }}</PostgresHost>
      <PostgresPort>{{ .Values.database.ports.http.targetPort }}</PostgresPort>
      <PostgresUser>{{ .Values.database.credentials.username }}</PostgresUser>
      <PostgresPassword>{{ .Values.database.credentials.password }}</PostgresPassword>
      <PostgresMainDb>{{ .Values.database.schemas.readarr.main }}</PostgresMainDb>
      <PostgresLogDb>{{ .Values.database.schemas.readarr.logs }}</PostgresLogDb>
      <PostgresCacheDb>{{ .Values.database.schemas.readarr.cache }}</PostgresCacheDb>
    </Config>
{{- end }}
