apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: {{ .Values.k8s.names.ingresses.prefix }}{{ .Values.observability.opentelemetryCollector.gateway.label }}{{ .Values.k8s.names.ingresses.suffix }}
  labels:
    chartVersion: {{ .Chart.Version }}
    env: {{ .Values.project.env }}

spec:
  entryPoints:
  - {{ .Values.traefik.ports.https.name }}

  routes:
  - kind: Rule
    match: Host(`{{ .Values.observability.opentelemetryCollector.gateway.host }}`)
    middlewares:
    - name: {{ .Values.k8s.names.middlewares.prefix }}{{ .Values.authelia.label }}{{ .Values.k8s.names.middlewares.suffix }}
      namespace: {{ .Values.k8s.namespace }}
    services:
    - kind: Service
      name: {{ .Values.k8s.names.services.prefix }}{{ .Values.observability.opentelemetryCollector.gateway.label }}{{ .Values.k8s.names.services.suffix }}
      port: {{ .Values.observability.opentelemetryCollector.gateway.ports.http.targetPort }}

  tls:
    certResolver: {{ .Values.traefik.resolverName }}
