apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.homepage.names.configMap }}

data:
  kubernetes.yaml: ""
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Dev:
      - Github:
        - abbr: GH
          href: https://github.com/
    - Social:
      - Reddit:
        - abbr: RE
          href: https://reddit.com/
    - Entertainment:
      - Invidious:
        - abbr: In
          href: https://api.invidious.io/
  services.yaml: |
    - Media:
      - Jellyfin:
          abbr: JE
          href: https://{{ .Values.jellyfin.host }}
          widget:
            type: jellyfin
            url: https://{{ .Values.jellyfin.host }}
            key: 6d65fa79175e41128fb097d3e2b3eec9
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
            enableUser: true # optional, defaults to false
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: false # optional, defaults to true
    - Dev:
      - Traefik:
          abbr: TR
          href: https://{{ .Values.traefik.host }}/dashboard/
          widget:
            type: traefik
            url: https://{{ .Values.traefik.host }}
      - Who am I?:
          href: https://{{ .Values.whoami.host }}
          description: TODO
  widgets.yaml: |
    # https://gethomepage.dev/widgets/info/resources/
    - resources:
        backend: resources
        expanded: true
        units: metric
        cpu: true
        memory: true
        uptime: true
        network: default
    # https://gethomepage.dev/widgets/info/search/
    - search:
        provider: [google, duckduckgo, brave]
        focus: true
        showSearchSuggestions: true
        target: _blank
  docker.yaml: ""