{{- if .Values.wikijs.enabled }}
{{- $pod := print .Values.k8s.names.pods.prefix (tpl .Values.wikijs.database.label $) .Values.k8s.names.pods.suffix }}
{{- $appVolume := "app-volume" }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $pod }}
  labels:
    app: {{ $pod }}

spec:
  replicas: {{ .Values.wikijs.database.replicasNb }}
  selector:
    matchLabels:
      app: {{ $pod }}
  template:
    metadata:
      labels:
        app: {{ $pod }}
    spec:
      containers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ tpl .Values.wikijs.database.label . }}{{ .Values.k8s.names.containers.suffix }}
        image: {{ .Values.wikijs.database.image }}
        resources:
          {{- toYaml .Values.wikijs.database.resources | nindent 10 }}
        ports:
        - name: {{ .Values.wikijs.database.ports.http.name }}
          containerPort: {{ .Values.wikijs.database.ports.http.targetPort }}
        env:
        - name: POSTGRES_USER
          value: "{{ tpl .Values.wikijs.database.credentials.username . }}"
        - name: POSTGRES_PASSWORD
          value: "{{ tpl .Values.wikijs.database.credentials.password . }}"
        - name: POSTGRES_DB
          value: "{{ tpl .Values.wikijs.database.name . }}"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: {{ $appVolume }}
          subPath: wikijs/db
      volumes:
      - name: {{ $appVolume }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.wikijs.storage.pvc . }}
{{- end }}
