apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.k8s.names.configMaps.prefix }}{{ .Values.traefik.label }}{{ .Values.k8s.names.configMaps.suffix }}

data:
  jellyfin-file-provider.yaml: |
    {{- if .Values.jellyfin.proxy.enable }}
    http:
      routers:
        jellyfin-local:
          entryPoints:
          - {{ .Values.traefik.ports.https.name }}
          {{- if or .Values.traefik.tls.selfSigned .Values.traefik.tls.wildcard }}
          tls: {}
          {{- else }}
          tls:
            certResolver: {{ .Values.traefik.resolverName }}
          {{- end }}
          service: jellyfin-local-proxy
          rule: Host(`{{ tpl .Values.jellyfin.host . }}`)
      services:
        jellyfin-local-proxy:
          loadBalancer:
            passHostHeader: false
            servers:
            - url: http://{{ .Values.jellyfin.proxy.host }}:{{ .Values.jellyfin.proxy.port }}
    {{- end }}
