apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.k8s.names.services.prefix }}{{ .Values.traefik.label }}{{ .Values.k8s.names.services.suffix }}

spec:
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: {{ .Values.traefik.ports.http.port }}
      targetPort: {{ .Values.traefik.ports.http.targetPort }}
      name: {{ .Values.traefik.ports.http.name }}
      nodePort: {{ .Values.traefik.ports.http.nodePort }}
    - protocol: TCP
      port: {{ .Values.traefik.ports.https.port }}
      targetPort: {{ .Values.traefik.ports.https.targetPort }}
      name: {{ .Values.traefik.ports.https.name }}
      nodePort: {{ .Values.traefik.ports.https.nodePort }}
  selector:
    app: {{ .Values.k8s.names.pods.prefix }}{{ .Values.traefik.label }}{{ .Values.k8s.names.pods.suffix }}
  type: LoadBalancer
  {{- if .Values.traefik.loadBalancerIP }}
  loadBalancerIP: {{ .Values.traefik.loadBalancerIP }}
  {{- end }}
