apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.media.database.names.pod }}
  labels:
    app: {{ .Values.media.database.names.pod }}

spec:
  replicas: {{ .Values.media.database.replicasNb }}
  selector:
    matchLabels:
      app: {{ .Values.media.database.names.pod }}
  template:
    metadata:
      labels:
        app: {{ .Values.media.database.names.pod }}
    spec:
      containers:
      - name: {{ .Values.media.database.names.container }}
        image: {{ .Values.media.database.image }}
        ports:
        - name: {{ .Values.media.database.ports.http.name }}
          containerPort: {{ .Values.media.database.ports.http.targetPort }}
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.media.database.credentials.username }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.media.database.credentials.password }}"
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/init-db.sh
          name: {{ .Values.media.database.names.configMap }}
          subPath: init-db.sh
        - mountPath: /var/lib/postgresql
          name: {{ .Values.media.storage.pv }}
          subPath: apps/postgres
      volumes:
      - name: {{ .Values.media.database.names.configMap }}
        configMap:
          name: {{ .Values.media.database.names.configMap }}
      - name: {{ .Values.media.storage.pv }}
        persistentVolumeClaim:
          claimName: {{ .Values.media.storage.pvc }}
