apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Values.media.database.names.ingress }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.traefik.ports.https.name }}
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.traefik.resolverName }}
  labels:
    chartVersion: {{ .Chart.Version }}
    env: {{ .Values.project.env }}

spec:
  rules:
  - host: {{ .Values.media.database.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.media.database.names.service }}
            port:
              number: {{ .Values.media.database.ports.http.targetPort }}
