{{- if .Values.observability.profiles.enable }}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.k8s.names.configMaps.prefix }}{{ .Values.observability.profiles.label }}{{ .Values.k8s.names.configMaps.suffix }}

data:
  pyroscope.yaml: |
    target: all

    server:
      http_listen_port: {{ .Values.observability.profiles.ports.http.targetPort }}

    storage:
      backend: filesystem
      filesystem:
        dir: /var/pyroscope/data
{{- end }}
