{{- if .Values.transmission.enable }}
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.k8s.names.services.prefix }}{{ .Values.transmission.label }}{{ .Values.k8s.names.services.suffix }}

spec:
  ports:
  - protocol: TCP
    name: {{ .Values.transmission.ports.http.name }}
    nodePort: {{ .Values.transmission.ports.http.nodePort }}
    port: {{ .Values.transmission.ports.http.targetPort }}
    targetPort: {{ .Values.transmission.ports.http.targetPort }}
  - protocol: TCP
    name: {{ .Values.transmission.ports.peer.name }}
    nodePort: {{ .Values.transmission.ports.peer.nodePort }}
    port: {{ .Values.transmission.ports.peer.targetPort }}
    targetPort: {{ .Values.transmission.ports.peer.targetPort }}
  - protocol: UDP
    name: {{ .Values.transmission.ports.peer.nameUdp }}
    nodePort: {{ .Values.transmission.ports.peer.nodePortUdp }}
    port: {{ .Values.transmission.ports.peer.targetPort }}
    targetPort: {{ .Values.transmission.ports.peer.targetPort }}
  selector:
    app: {{ .Values.k8s.names.pods.prefix }}{{ .Values.transmission.label }}{{ .Values.k8s.names.pods.suffix }}
  type: NodePort
{{- end }}
