{{- $pod := print .Values.k8s.names.pods.prefix .Values.observability.dashboard.label .Values.k8s.names.pods.suffix }}
{{- $appVolume := "app-volume" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $pod }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $pod }}
  template:
    metadata:
      labels:
        app: {{ $pod }}
    spec:
      containers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ .Values.observability.dashboard.label }}{{ .Values.k8s.names.containers.suffix }}
        image: {{ .Values.observability.dashboard.image }}
        ports:
        - containerPort: {{ .Values.observability.dashboard.ports.http.targetPort }}
        volumeMounts:
        - name: conf
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
        - name: conf
          mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
          subPath: datasources.yaml
        - name: conf
          mountPath: /etc/grafana/provisioning/dashboards/media.yaml
          subPath: dashboards-providers.yaml
        - name: conf
          mountPath: /var/lib/grafana/dashboards/media/jellyfin.json
          subPath: jellyfin.json
        - name: conf
          mountPath: /var/lib/grafana/dashboards/media/transmission.json
          subPath: nas.json
        - name: conf
          mountPath: /var/lib/grafana/dashboards/infra/nas.json
          subPath: transmission.json
        - mountPath: /var/lib/grafana
          name: {{ $appVolume }}
          subPath: grafana/data
        - mountPath: /var/lib/grafana/plugins
          name: {{ $appVolume }}
          subPath: grafana/plugins
        - mountPath: /etc/grafana/provisioning
          name: {{ $appVolume }}
          subPath: grafana/provisioning
#        readinessProbe:
#          failureThreshold: 3
#          httpGet:
#            path: /robots.txt
#            port: 3000
#            scheme: HTTP
#          initialDelaySeconds: 10
#          periodSeconds: 30
#          successThreshold: 1
#          timeoutSeconds: 2
#        livenessProbe:
#          failureThreshold: 3
#          initialDelaySeconds: 30
#          periodSeconds: 10
#          successThreshold: 1
#          tcpSocket:
#            port: 3000
#          timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
      volumes:
      - name: {{ $appVolume }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.observability.pvc . }}
      - name: conf
        configMap:
          name: {{ .Values.k8s.names.configMaps.prefix }}{{ .Values.observability.dashboard.label }}{{ .Values.k8s.names.configMaps.suffix }}
