apiVersion: traefik.io/v1alpha1
kind: Middleware

metadata:
  name: {{ .Values.authelia.names.middleware }}
  labels:
    chartVersion: {{ .Chart.Version }}
    env: {{ .Values.project.env }}

spec:
  forwardAuth:
    address: 'http://{{ .Values.authelia.names.service }}:{{ .Values.authelia.ports.http.targetPort }}/api/authz/forward-auth'
    authResponseHeaders:
      - 'Remote-User'
      - 'Remote-Groups'
      - 'Remote-Email'
      - 'Remote-Name'
    trustForwardHeader: true
