apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.k8s.names.services.prefix }}{{ .Values.lldap.label }}{{ .Values.k8s.names.services.suffix }}

spec:
  selector:
    app: {{ .Values.k8s.names.pods.prefix }}{{ .Values.lldap.label }}{{ .Values.k8s.names.pods.suffix }}
  ports:
  - name: {{ .Values.lldap.ports.http.name }}
    port: {{ .Values.lldap.ports.http.targetPort }}
    targetPort: {{ .Values.lldap.ports.http.targetPort }}
  - name: {{ .Values.lldap.ports.ldap.name }}
    port: {{ .Values.lldap.ports.ldap.targetPort }}
    targetPort: {{ .Values.lldap.ports.ldap.targetPort }}
