{{- if .Values.qbittorrent.enable }}
{{- $pod := print .Values.k8s.names.pods.prefix .Values.qbittorrent.label .Values.k8s.names.pods.suffix }}
{{- $configMap := "config-map" }}
{{- $appVolume := "app-volume" }}
{{- $mediaVolume := "media-volume" }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $pod }}
  labels:
    app: {{ $pod }}

spec:
  replicas: {{ .Values.qbittorrent.replicasNb }}
  selector:
    matchLabels:
      app: {{ $pod }}
  template:
    metadata:
      labels:
        app: {{ $pod }}
    spec:
      containers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ .Values.qbittorrent.label }}{{ .Values.k8s.names.containers.suffix }}
        image: {{ .Values.qbittorrent.image }}
        resources:
          {{- toYaml .Values.qbittorrent.resources | nindent 10 }}
        ports:
        - name: {{ .Values.qbittorrent.ports.http.name }}
          containerPort: {{ .Values.qbittorrent.ports.http.targetPort }}
        - name: {{ .Values.qbittorrent.ports.tcp.name }}
          containerPort: {{ .Values.qbittorrent.ports.tcp.targetPort }}
        - name: {{ .Values.qbittorrent.ports.udp.name }}
          containerPort: {{ .Values.qbittorrent.ports.udp.targetPort }}
          protocol: UDP
        env:
        - name: PUID
          value: "{{ .Values.media.system.userId }}"
        - name: PGID
          value: "{{ .Values.media.system.groupId }}"
        - name: UMASK
          value: "{{ .Values.media.system.umask }}"
        - name: WEBUI_PORT
          value: "{{ .Values.qbittorrent.ports.http.targetPort }}"
        - name: TORRENTING_PORT
          value: "{{ .Values.qbittorrent.ports.tcp.targetPort }}"
        volumeMounts:
        - mountPath: /config/qBittorrent
          name: {{ $appVolume }}
          subPath: qbittorrent/config
        - mountPath: {{ .Values.media.system.data.path }}
          name: {{ $mediaVolume }}
          subPath: downloads/qbittorrent
      initContainers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ .Values.qbittorrent.label }}-init{{ .Values.k8s.names.containers.suffix }}
        image: python:3-slim
        command: ['sh', '-c', 'cp -f /qBittorrent.conf /config/qBittorrent/ && python /update_password.py']
        volumeMounts:
        - mountPath: /update_password.py
          name: {{ $configMap }}
          subPath: update_password.py
        - mountPath: /qBittorrent.conf
          name: {{ $configMap }}
          subPath: qBittorrent.conf
        - mountPath: /config/qBittorrent
          name: {{ $appVolume }}
          subPath: qbittorrent/config
      volumes:
      - name: {{ $mediaVolume }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.transmission.pvc.media . }}
      - name: {{ $appVolume }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.transmission.pvc.app . }}
      - name: {{ $configMap }}
        configMap:
          name: {{ .Values.k8s.names.configMaps.prefix }}{{ .Values.qbittorrent.label }}{{ .Values.k8s.names.configMaps.suffix }}
{{- end }}
