apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.k8s.names.services.prefix }}{{ .Values.observability.labelProxy.label }}{{ .Values.k8s.names.services.suffix }}
spec:
  ports:
  - protocol: TCP
    name: {{ .Values.observability.labelProxy.ports.http.name }}
    port: {{ .Values.observability.labelProxy.ports.http.targetPort }}
    targetPort: {{ .Values.observability.labelProxy.ports.http.targetPort }}
  selector:
    app: {{ .Values.k8s.names.pods.prefix }}{{ .Values.observability.labelProxy.label }}{{ .Values.k8s.names.pods.suffix }}
