apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.k8s.names.services.prefix }}{{ tpl .Values.bookstack.database.label . }}{{ .Values.k8s.names.services.suffix }}

spec:
  ports:
  - protocol: TCP
    name: {{ .Values.bookstack.database.ports.http.name }}
    port: {{ .Values.bookstack.database.ports.http.targetPort }}
  selector:
    app: {{ .Values.k8s.names.services.prefix }}{{ tpl .Values.bookstack.database.label . }}{{ .Values.k8s.names.pods.suffix }}
