{{- $pod := print .Values.k8s.names.pods.prefix .Values.bookstack.label .Values.k8s.names.pods.suffix }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $pod }}
  labels:
    app: {{ $pod }}

spec:
  replicas: {{ .Values.bookstack.replicasNb }}
  selector:
    matchLabels:
      app: {{ $pod }}
  template:
    metadata:
      labels:
        app: {{ $pod }}
    spec:
      containers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ .Values.bookstack.label }}{{ .Values.k8s.names.containers.suffix }}
        image: {{ .Values.bookstack.image }}
        ports:
        - name: {{ .Values.bookstack.ports.http.name }}
          containerPort: {{ .Values.bookstack.ports.http.targetPort }}
        env:
        - name: PUID
          value: "{{ .Values.bookstack.system.userId }}"
        - name: PGID
          value: "{{ .Values.bookstack.system.groupId }}"
        - name: APP_DEBUG
          value: "{{ .Values.bookstack.appDebug }}"
        - name: APP_URL
          value: "https://{{ .Values.bookstack.host }}"
        - name: APP_KEY
          value: "{{ .Values.bookstack.appKey }}"
        - name: DB_HOST
          value: "{{ .Values.k8s.names.services.prefix }}{{ .Values.bookstack.database.label }}{{ .Values.k8s.names.services.suffix }}"
        - name: DB_PORT
          value: "{{ .Values.bookstack.database.ports.http.targetPort }}"
        - name: DB_USERNAME
          value: "{{ .Values.bookstack.database.credentials.username }}"
        - name: DB_PASSWORD
          value: "{{ .Values.bookstack.database.credentials.password }}"
        - name: DB_DATABASE
          value: "{{ .Values.bookstack.database.name }}"
        # OIDC configuration
        - name: AUTH_METHOD
          value: oidc
        - name: OIDC_NAME
          value: Authelia
        - name: OIDC_DISPLAY_NAME_CLAIMS
          value: name
        - name: OIDC_CLIENT_ID
          value: "{{ .Values.bookstack.oidc.clientId }}"
        - name: OIDC_CLIENT_SECRET
          value: "{{ .Values.bookstack.oidc.clientSecret }}"
        - name: OIDC_ISSUER
          value: "https://{{ .Values.authelia.host }}"
        - name: OIDC_ISSUER_DISCOVER
          value: "true"
        volumeMounts:
        - mountPath: /app/config
          name: {{ .Values.bookstack.storage.pvc }}
          subPath: bookstack/config
      volumes:
      - name: {{ .Values.bookstack.storage.pvc }}
        persistentVolumeClaim:
          claimName: {{ .Values.bookstack.storage.pvc }}
