apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.bookstack.database.names.service }}

spec:
  ports:
  - protocol: TCP
    name: {{ .Values.bookstack.database.ports.http.name }}
    port: {{ .Values.bookstack.database.ports.http.targetPort }}
  selector:
    app: {{ .Values.bookstack.database.names.pod }}
