apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.k8s.names.services.prefix }}{{ .Values.transmission.label }}{{ .Values.k8s.names.services.suffix }}

spec:
  ports:
  - protocol: TCP
    name: {{ .Values.transmission.ports.http.name }}
    port: {{ .Values.transmission.ports.http.targetPort }}
  - protocol: TCP
    name: {{ .Values.transmission.ports.tcp.name }}
    port: {{ .Values.transmission.ports.tcp.targetPort }}
  - protocol: UDP
    name: {{ .Values.transmission.ports.udp.name }}
    port: {{ .Values.transmission.ports.udp.targetPort }}
  selector:
    app: {{ .Values.k8s.names.pods.prefix }}{{ .Values.transmission.label }}{{ .Values.k8s.names.pods.suffix }}
