{{- $pod := print .Values.k8s.names.pods.prefix .Values.observability.metrics.label .Values.k8s.names.pods.suffix }}
{{- $appVolume := "app-volume" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $pod }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $pod }}
  template:
    metadata:
      labels:
        app: {{ $pod }}
    spec:
      containers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ .Values.observability.metrics.label }}{{ .Values.k8s.names.containers.suffix }}
        image: {{ .Values.observability.metrics.image }}
        resources:
          {{- toYaml .Values.observability.metrics.resources | nindent 10 }}
        args:
        - "-storageDataPath=/storage"
        - "-retentionPeriod=1y"
        - "-loggerFormat={{ .Values.observability.metrics.logging.format }}"
        - "-loggerLevel={{ .Values.observability.metrics.logging.level }}"
        ports:
        - containerPort: {{ .Values.observability.metrics.ports.http.targetPort }}
        volumeMounts:
        - mountPath: /storage
          name: {{ $appVolume }}
          subPath: victoria-metrics
      volumes:
      - name: {{ $appVolume }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.observability.pvc . }}
