apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.qbittorrent.names.configMap }}

data:
  init.sh: |
    #!/bin/sh
    exit 0
  core.conf: |
    WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
