{{- if .Values.deluge.enable }}
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.k8s.names.services.prefix }}{{ .Values.deluge.label }}{{ .Values.k8s.names.services.suffix }}

spec:
  ports:
  - protocol: TCP
    name: {{ .Values.deluge.ports.http.name }}
    port: {{ .Values.deluge.ports.http.targetPort }}
  - protocol: TCP
    name: {{ .Values.deluge.ports.tcp.name }}
    port: {{ .Values.deluge.ports.tcp.targetPort }}
  - protocol: UDP
    name: {{ .Values.deluge.ports.udp.name }}
    port: {{ .Values.deluge.ports.udp.targetPort }}
  selector:
    app: {{ .Values.k8s.names.pods.prefix }}{{ .Values.deluge.label }}{{ .Values.k8s.names.pods.suffix }}
{{- end }}
