{{- if .Values.deluge.enabled }}
{{- $pod := print .Values.k8s.names.pods.prefix .Values.deluge.label .Values.k8s.names.pods.suffix }}
{{- $configMap := "config-map" }}
{{- $appVolume := "app-volume" }}
{{- $mediaVolume := "media-volume" }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $pod }}
  labels:
    app: {{ $pod }}

spec:
  replicas: {{ .Values.deluge.replicasNb }}
  selector:
    matchLabels:
      app: {{ $pod }}
  template:
    metadata:
      labels:
        app: {{ $pod }}
    spec:
      containers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ .Values.deluge.label }}{{ .Values.k8s.names.containers.suffix }}
        image: {{ .Values.deluge.image }}
        resources:
          {{- toYaml .Values.deluge.resources | nindent 10 }}
        ports:
        - name: {{ .Values.deluge.ports.http.name }}
          containerPort: {{ .Values.deluge.ports.http.targetPort }}
        - name: {{ .Values.deluge.ports.tcp.name }}
          containerPort: {{ .Values.deluge.ports.tcp.targetPort }}
        - name: {{ .Values.deluge.ports.udp.name }}
          containerPort: {{ .Values.deluge.ports.udp.targetPort }}
          protocol: UDP
        env:
        - name: PUID
          value: "{{ .Values.media.system.userId }}"
        - name: PGID
          value: "{{ .Values.media.system.groupId }}"
        - name: UMASK
          value: "{{ .Values.media.system.umask }}"
        - name: DELUGE_LOGLEVEL
          value: "{{ .Values.deluge.logLevel }}"
        volumeMounts:
        - mountPath: /config
          name: {{ $appVolume }}
          subPath: deluge/config
        - mountPath: {{ .Values.media.system.data.path }}
          name: {{ $mediaVolume }}
          subPath: downloads/deluge
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.deluge.ports.http.targetPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
      initContainers:
      - name: {{ .Values.k8s.names.containers.prefix }}{{ .Values.deluge.label }}-init{{ .Values.k8s.names.containers.suffix }}
        image: curlimages/curl:8.11.1
        command: ['sh', '-c', '/init.sh']
        volumeMounts:
        - mountPath: /init.sh
          name: {{ $configMap }}
          subPath: init.sh
        - mountPath: /core.conf
          name: {{ $configMap }}
          subPath: core.conf
        - mountPath: /config
          name: {{ $appVolume }}
          subPath: deluge/config
      volumes:
      - name: {{ $mediaVolume }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.transmission.pvc.media . }}
      - name: {{ $appVolume }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.transmission.pvc.app . }}
      - name: {{ $configMap }}
        configMap:
          name: {{ .Values.k8s.names.configMaps.prefix }}{{ .Values.deluge.label }}{{ .Values.k8s.names.configMaps.suffix }}
          defaultMode: 0555
{{- end }}
