{{- if .Values.observability.otelCollector.gateway.enable }}
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.k8s.names.services.prefix }}{{ tpl .Values.observability.otelCollector.gateway.label . }}{{ .Values.k8s.names.services.suffix }}

spec:
  ports:
  - protocol: TCP
    name: {{ .Values.observability.otelCollector.gateway.ports.grpc.name }}
    port: {{ .Values.observability.otelCollector.gateway.ports.grpc.targetPort }}
    targetPort: {{ .Values.observability.otelCollector.gateway.ports.grpc.targetPort }}
  - protocol: TCP
    name: {{ .Values.observability.otelCollector.gateway.ports.http.name }}
    port: {{ .Values.observability.otelCollector.gateway.ports.http.targetPort }}
    targetPort: {{ .Values.observability.otelCollector.gateway.ports.http.targetPort }}
  selector:
    app: {{ .Values.k8s.names.pods.prefix }}{{ tpl .Values.observability.otelCollector.gateway.label . }}{{ .Values.k8s.names.pods.suffix }}
{{- end }}
