apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.homepage.names.configMap }}

data:
  kubernetes.yaml: ""
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Dev:
      - Github:
        - abbr: GH
          href: https://github.com/
    - Social:
      - Reddit:
        - abbr: RE
          href: https://reddit.com/
    - Entertainment:
      - Invidious:
        - abbr: In
          href: https://api.invidious.io/
  services.yaml: |
    - Media:
      - Jellyfin:
          abbr: JE
          href: https://{{ .Values.jellyfin.host }}
          widget:
            type: jellyfin
            url: https://{{ .Values.jellyfin.host }}{{ .Values.jellyfin.baseUrl }}
            key: 6d65fa79175e41128fb097d3e2b3eec9
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
            enableUser: true # optional, defaults to false
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: false # optional, defaults to true
      - JellySeerr:
          abbr: JS
          href: https://{{ .Values.jellyseerr.host }}
          widget:
            type: jellyseerr
            url: https://{{ .Values.jellyseerr.host }}
            key: {{ .Values.jellyseerr.apiKey }}
      - Prowlarr:
          abbr: PR
          href: https://{{ .Values.prowlarr.host }}
          widget:
            type: prowlarr
            url: https://{{ .Values.prowlarr.host }}
            key: {{ .Values.prowlarr.apiKey }}
      - Radarr:
          abbr: RA
          href: https://{{ .Values.radarr.host }}
          widget:
            type: radarr
            url: https://{{ .Values.radarr.host }}
            key: {{ .Values.radarr.apiKey }}
      - Readarr:
          abbr: RE
          href: https://{{ .Values.readarr.host }}
          widget:
            type: readarr
            url: https://{{ .Values.readarr.host }}
            key: {{ .Values.readarr.apiKey }}
      - Sonarr:
          abbr: SR
          href: https://{{ .Values.sonarr.host }}
          widget:
            type: sonarr
            url: https://{{ .Values.sonarr.host }}
            key: {{ .Values.sonarr.apiKey }}
      - FlareSolverr:
          abbr: FS
          href: https://{{ .Values.flaresolverr.host }}
    - Files:
      - Deluge:
          abbr: DL
          href: https://{{ .Values.deluge.host }}
          widget:
            type: deluge
            url: https://{{ .Values.deluge.host }}
            password: {{ .Values.deluge.credentials.password }}
            enableLeechProgress: true
      - QBitTorrent:
          abbr: QB
          href: https://{{ .Values.qbittorrent.host }}
          widget:
            type: qbittorrent
            url: https://{{ .Values.qbittorrent.host }}
            username: {{ .Values.qbittorrent.credentials.username }}
            password: {{ .Values.qbittorrent.credentials.password }}
            enableLeechProgress: true
    - Dev:
      - Traefik:
          abbr: TR
          href: https://{{ .Values.traefik.host }}/dashboard/
          widget:
            type: traefik
            url: https://{{ .Values.traefik.host }}
      - Who am I?:
          href: https://{{ .Values.whoami.host }}
          description: Tiny Go webserver that prints os information and HTTP request to output
  widgets.yaml: |
    # https://gethomepage.dev/widgets/info/resources/
    - resources:
        backend: resources
        expanded: true
        units: metric
        cpu: true
        memory: true
        uptime: true
        network: default
    # https://gethomepage.dev/widgets/info/search/
    - search:
        provider: [google, duckduckgo, brave]
        focus: true
        showSearchSuggestions: true
        target: _blank
  docker.yaml: ""
