apiVersion: v1
kind: Secret

type: kubernetes.io/service-account-token

metadata:
  name: {{ .Values.homepage.names.secret }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.homepage.names.serviceAccount }}
