apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: {{ .Values.k8s.namespace }}--{{ .Values.k8s.names.roles.prefix }}{{ .Values.homepage.label }}{{ .Values.k8s.names.roles.suffix }}

rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.io
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
